<?php

//
//  FIR Positions
//
$firPositions = [

    // Bagotville
    'CYBG_GND', 'CYBG_TWR',
    'CYBG_APP', 
    'CYBG_ATIS',

    // St-Hubert
    'CYHU_GND', 'CYHU_TWR',
    'CYHU_ATIS',

    // Ottawa
    'CYOW_DEL', 'CYOW_GND', 'CYOW_TWR',
    'CYOW_DEP', 'CYOW_APP',
    'CYOW_ATIS',

    // Québec
    'CYQB_GND', 'CYQB_TWR',
    'CYQB_APP',
    'CYQB_ATIS',

    // Chicoutimi
    'CYRC_GND', 'CYRC_TWR',
    'CYRC_ATIS',

    // Montréal
    'CYUL_DEL', 'CYUL_A_GND', 'CYUL_GND', 'CYUL_TWR',
    'CYUL_DEP', 'CYUL_S_DEP', 'CYUL_N_DEP',
    'CYUL_APP', 'CYUL_L_APP', 'CYUL_S_APP', 'CYUL_N_APP', 'CYUL_VF_APP',
    'CYUL_ATIS',

    // Centers
    'MTL_LE_CTR', 'MTL_MC_CTR', 'MTL_FG_CTR', 'MTL_BZ_CTR',
    'MTL_RW_CTR', 'MTL_HV_CTR', 'MTL_GL_CTR', 'MTL_NK_CTR',
    'MTL_CTR',

    // Other
    'CPTL_APP',

];

//
//  FIR Airports
//
$atisEnabledAirports = [
    'CYUL', 'CYOW', 'CYQB', 'CYHU', 'CYRC',
];

$firAirports = [

    // Class C
    'CYUL' => 'Montréal/Pierre Elliott Trudeau International',
    'CYHU' => 'Montréal/Saint-Hubert',
    'CYQB' => 'Québec City/Jean Lesage International',
    'CYOW' => 'Ottawa/Macdonald-Cartier International',
    'CYRC' => 'Chicoutimi/St-Honoré',

    // Class D
    'CYJN' => 'St-Jean',

    // Class E
    'CYBC' => 'Baie-Comeau',
    'CYFB' => 'Iqaluit',
    'CYGP' => 'Michel-Pouliot Gaspé',
    'CYND' => 'Gatineau-Ottawa Executive',
    'CYGL' => 'La Grande Rivière',
    'CYMX' => 'Montréal/Mirabel International',
    'CYYY' => 'Mont-Joli',
    'CYUY' => 'Rouyn-Noranda',
    'CYZV' => 'Sept-Îles',
    'CYVO' => 'Val-d\'Or',
    'CYWK' => 'Wabush',

    // Other
    'CZEM' => 'Eastmain River',
    'CZBM' => 'Bromont (Roland Désourdy)',
    'CYZG' => 'Salluit',
    'CYXK' => 'Rimouski',
    'CYVP' => 'Kuujjuaq',
    'CYVB' => 'Bonaventure',
    'CYTQ' => 'Tasiujaq',
    'CYTF' => 'Alma',
    'CYSZ' => 'Ste-Anne-des-Monts',
    'CYSG' => 'St-Georges',
    'CYSC' => 'Sherbrooke',
    'CYRQ' => 'Trois-Rivières',
    'CYRJ' => 'Roberval',
    'CYRI' => 'Rivière-du-Loup',
    'CYPX' => 'Puvirnituq',
    'CYPP' => 'Parent',
    'CYPN' => 'Port-Menier',
    'CYPH' => 'Inukjuak',
    'CYOY' => 'Valcartier (W/C J.H.L. (Joe) Lecomte) Heliport',
    'CYNM' => 'Matagami',
    'CYNC' => 'Wemindji',
    'CYNA' => 'Natashquan',
    'CYMW' => 'Maniwaki',
    'CYMU' => 'Umiujaq',
    'CYMT' => 'Chibougamau/Chapais',
    'CYML' => 'Charlevoix',
    'CYME' => 'Matane',
    'CYLU' => 'Kangiqsualujjuaq (Georges River)',
    'CYLQ' => 'La Tuque',
    'CYLA' => 'Aupaluk',
    'CYKQ' => 'Waskaganish',
    'CYKO' => 'Akulivik',
    'CYKL' => 'Schefferville',
    'CYKG' => 'Kangiqsujuaq (Wakeham Bay)',
    'CYIK' => 'Ivujivik',
    'CYIF' => 'St-Augustin',
    'CYHU' => 'Montréal/St-Hubert',
    'CYHR' => 'Chevery',
    'CYHH' => 'Nemiscau',
    'CYHA' => 'Quaqtaq',
    'CYGW' => 'Kuujjuarapik',
    'CYGV' => 'Havre St-Pierre',
    'CYGR' => 'Îles-de-la-Madeleine',
    'CYFJ' => 'La Macaza/Mont-Tremblant International Inc',
    'CYFE' => 'Forestville',
    'CYEY' => 'Amos/Magny',
    'CYES' => 'Edmundston',
    'CYDO' => 'Dolbeau-St-Félicien',
    'CYBX' => 'Lourdes-de-Blanc-Sablon',
    'CYBG' => 'Bagotville',
    'CYAS' => 'Kangirsuk',
    'CYAH' => 'La Grande-4',
    'CYAD' => 'La Grande-3',
    'CVB6' => 'Val-d’Or (Huard) Seaplane Base',
    'CTY5' => 'Rougemont',
    'CTY3' => 'Cascades Seaplane Base',
    'CTX2' => 'Lac Trevet Seaplane Base',
    'CTV2' => 'Lac-des-Écorces Seaplane Base',
    'CTU5' => 'La Tabatière',
    'CTU2' => 'Fontanges',
    'CTT5' => 'La Romaine',
    'CTS3' => 'Lac Berthelot Seaplane Base',
    'CTR6' => 'St-Basile (Marcotte)',
    'CTR4' => 'Granby/Artopex Plus Heliport',
    'CTQ6' => 'St-Anselme',
    'CTQ3' => 'Aguanish Seaplane Base',
    'CTQ2' => 'Stanstead/Weller',
    'CTP9' => 'Kattiniq/Donaldson',
    'CTP4' => 'Lac Pau (Caniapiscau) Seaplane Base',
    'CTP3' => 'Barrage Gouin Seaplane Base',
    'CTN3' => 'Lac Beauregard Seaplane Base',
    'CTM8' => 'Témiscouata-sur-le-Lac Seaplane Base',
    'CTM3' => 'Chutes-des-Passes/Lac Margane Seaplane Base',
    'CTK6' => 'Kegaska',
    'CTK2' => 'Senneterre',
    'CTJ5' => 'Québec/Hôpital de L\'Enfant-Jésus Heliport',
    'CTI3' => 'Ottawa/Gatineau Seaplane Base',
    'CTH9' => 'St-Augustin Heliport',
    'CTH7' => 'Rivière-aux-Saumons',
    'CTH6' => 'La Tuque Seaplane Base',
    'CTH5' => 'Harrington Harbour Heliport',
    'CTH3' => 'Grandes-Bergeronnes',
    'CTG3' => 'Du Rocher-Percé (Pabok)',
    'CTG2' => 'Montréal/St-Hubert Helicraft Heliport',
    'CTF3' => 'Causapscal',
    'CTE3' => 'Havre St-Pierre Seaplane Base',
    'CTD4' => 'Baie-St-Paul Heliport',
    'CTD3' => 'Lac Sébastien Seaplane Base',
    'CTC2' => 'St-Alphonse/Lac Cloutier Seaplane Base',
    'CTB6' => 'Tête-à-la-Baleine',
    'CTA9' => 'Ottawa/Gatineau (Casino) Heliport',
    'CTA5' => 'Val-d\'Or/Rivière Piché Seaplane Base',
    'CTA4' => 'St-Bruno-de-Guigues',
    'CTA3' => 'Île aux Coudres',
    'CTA2' => 'Sept-Îles (Hydro-Québec) Heliport',
    'CSZ9' => 'Schefferville/Squaw Lake Seaplane Base',
    'CSZ8' => 'Montréal (Sacré-Coeur) Heliport',
    'CSZ7' => 'Chibougamau/Lac Caché Seaplane Base',
    'CSZ6' => 'St-Jérôme (Hydro-Québec) Heliport',
    'CSZ4' => 'St-Frédéric',
    'CSZ3' => 'Mont-Tremblant/St-Jovite',
    'CSY8' => 'Natashquan (Lac de l\'Avion) Seaplane Base',
    'CSY6' => 'Poste Lemoyne (Complex LG-3) Heliport',
    'CSY5' => 'Valleyfield (Transport BRS Inc) Heliport',
    'CSY4' => 'St-Donat',
    'CSY3' => 'Sorel',
    'CSX5' => 'St-Mathias/Grant',
    'CSX3' => 'Richelieu',
    'CSW9' => 'Ste-Véronique Seaplane Base',
    'CSW5' => 'Montréal (Bell) Heliport',
    'CSV9' => 'St-Mathias Seaplane Base',
    'CSV7' => 'Rivière Témiscamie Seaplane Base',
    'CSV3' => 'Bécancour Heliport',
    'CSV2' => 'Ste-Agathe (AIM) Heliport',
    'CSU7' => 'Lac-à-la-Tortue QC (water aerodrome) Seaplane Base',
    'CSU5' => 'Weymontachie',
    'CSU3' => 'St-Hyacinthe',
    'CSU2' => 'Chisasibi',
    'CST8' => 'Montréal/Marina Venise Seaplane Base',
    'CST7' => 'St-Lambert-de-Lauzon',
    'CST6' => 'Clova/Lac Duchamp Seaplane Base',
    'CST3' => 'Montréal/St-Lazare',
    'CST2' => 'Montréal/Marina Venise Heliport',
    'CSS7' => 'Lac-à-Beauce Seaplane Base',
    'CSS4' => 'St-Dominique',
    'CSS3' => 'Montréal/Les Cèdres',
    'CSS2' => 'Rivière-du-Loup Heliport',
    'CSR8' => 'La Sarre',
    'CSR3' => 'Victoriaville',
    'CSQ3' => 'Valcourt',
    'CSP9' => 'Ste-Anne-du-Lac Seaplane Base',
    'CSP7' => 'Val-d\'Or (St-Pierre) Seaplane Base',
    'CSP6' => 'Montréal/Aéroparc Ìle Perrot',
    'CSP5' => 'St-Mathias',
    'CSN9' => 'Baie-Comeau/Héli-Manicouagan Heliport',
    'CSN8' => 'Québec/Lac St-Augustin Seaplane Base',
    'CSN7' => 'Farnham',
    'CSN5' => 'Stanhope',
    'CSN3' => 'St-Jérôme',
    'CSN2' => 'Montréal/Kruger Heliport',
    'CSM8' => 'Sept-Îles/Lac Rapides Seaplane Base',
    'CSM5' => 'St-Michel-des-Saints',
    'CSM3' => 'Thetford Mines',
    'CSL9' => 'Baie-Comeau (Manic 1)',
    'CSL5' => 'St-Victor-de-Beauce',
    'CSL3' => 'Lac-à-la-Tortue',
    'CSL2' => 'La Sarre Heliport',
    'CSK9' => 'Nicolet Heliport',
    'CSK5' => 'St-Raymond/Paquet',
    'CSK4' => 'Mansonville',
    'CSK3' => 'Montréal/Mascouche',
    'CSJ5' => 'St-Louis-de-France',
    'CSJ4' => 'Louiseville',
    'CSJ2' => 'Kanawata Aeroparc',
    'CSH9' => 'Montreal East (AIM) Heliport',
    'CSH8' => 'Manic 5/Lac Louise Seaplane Base',
    'CSH6' => 'Montréal/Les Cèdres Heliport',
    'CSH5' => 'St-Ferdinand',
    'CSH4' => 'Lebel-sur-Quévillon',
    'CSH2' => 'Isle-aux-Grues',
    'CSG9' => 'Sagard Heliport',
    'CSG7' => 'Sherbrooke (CHUS)/François Desourdy Heliport',
    'CSG5' => 'St-Jean Chrysostome',
    'CSG3' => 'Joliette',
    'CSF3' => 'Poste Montagnais (Mile 134)',
    'CSE9' => 'Parent Seaplane Base',
    'CSE6' => 'Mistissini Seaplane Base',
    'CSE5' => 'Montmagny',
    'CSE4' => 'Lachute',
    'CSE3' => 'Lourdes-de-Joliette',
    'CSE2' => 'Chibougamau (Hydro-Québec) Heliport',
    'CSD9' => 'Parc Gatineau Seaplane Base',
    'CSD6' => 'Baie-Comeau Seaplane Base',
    'CSD5' => 'Fermont Heliport',
    'CSD4' => 'Mont-Laurier',
    'CSD3' => 'Salaberry de Valleyfield',
    'CSC6' => 'Amos (Lac Figuery) Seaplane Base',
    'CSC5' => 'Lac Etchemin',
    'CSC3' => 'Drummondville',
    'CSB6' => 'Montebello Seaplane Base',
    'CSB4' => 'Chibougamau Heliport',
    'CSB3' => 'St-Mathieu-de-Beloeil',
    'CSA8' => 'Saguenay (Harvey) Seaplane Base',
    'CSA7' => 'Drummondville Seaplane Base',
    'CSA5' => 'Saguenay/St-Charles-de-Bourget Seaplane Base',
    'CSA4' => 'Montréal/Boisvert & Fils Seaplane Base',
    'CSA2' => 'Lac Agile (Mascouche)',
    'CRT2' => 'Rivière Témiscamie (Air Roberval Ltée)',
    'CRM3' => 'Richelieu/Messier',
    'CRG3' => 'Carignan (Bouthillier)',
    'CRB7' => 'Rivière Blanche/Cardinal Aviation Seaplane Base',
    'CRB5' => 'Rivière Bell',
    'CRB4' => 'Rivière Bonnard',
    'CPZ6' => 'Montréal/Point Zero Heliport',
    'CPT9' => 'Pintendre',
    'CPP8' => 'Montréal/Passport Hélico Heliport',
    'CPM3' => 'Pourvoirie Mirage',
    'CPH4' => 'Dolbeau-Mistassini/Potvin Heli-base, Heliport',
    'COR2' => 'Val-d’Or (St-Pierre) Heliport',
    'CNV9' => 'Québec/Neuville',
    'CNC2' => 'Cornwall (Nav Centre) Heliport',
    'CMT2' => 'Mont-Tremblant (Lac Maskinongé) Seaplane Base',
    'CMS3' => 'St-Michel-des-Saints (Marina le Nautique) Seaplane Base',
    'CMN5' => 'Manic-5',
    'CMN3' => 'St-Michel-de-Napierville',
    'CML9' => 'St-Michel Heliport',
    'CML8' => 'St-Mathieu-de-Laprairie',
    'CMH4' => 'Montréal/Mirabel Hélico Heliport',
    'CLS2' => 'Val-d\'Or/Lac Stabell Seaplane Base',
    'CLP3' => 'Lac Polaris (Pourvoirie Mirage Inc) Seaplane Base',
    'CLP2' => 'Montréal/Laval (Artopex Plus) Heliport',
    'CLL3' => 'Lac Lamothe Seaplane Base',
    'CLK4' => 'St-Michel-des-Saints/Lac Kaiagamac Seaplane Base',
    'CLB6' => 'La Grande-4/Lac de la Falaise Seaplane Base',
    'CKT6' => 'St-Remi-D\'Amherst/Kanata Tremblant Resort Heliport',
    'CJO2' => 'Joliette/St-Thomas',
    'CJF2' => 'Carignan/Rivière L’Acadie Seaplane Base',
    'CHT3' => 'Mont-Tremblant/St-Jovite Héli- Tremblant Heliport',
    'CHS5' => 'Montréal/Heliport Senneville Heliport',
    'CHP3' => 'Mont-Tremblant/Heliport P3 Heliport',
    'CHA3' => 'Montréal/Hydro Aéroport de Montréal Seaplane Base',
    'CHA2' => 'St-Étienne-des-Grès/Hydravion Aventure Seaplane Base',
    'CGD2' => 'Alma (Rivière La Grande Décharge) Seaplane Base',
    'CFX5' => 'Renard',
    'CES2' => 'St-Esprit',
    'CEL8' => 'Éléonore',
    'CEH8' => 'Montréal/Laval (Évasion Hélicoptère) Heliport',
    'CDE2' => 'Lac-des-Écorces/Heliport Belle-Île Heliport',
    'CDD3' => 'Ste-Agnès-de-Dundee',
    'CCU2' => 'St-Cuthbert (Ulm Québec)',
    'CCS7' => 'Chicoutimi (C.H. de Chicoutimi) Heliport',
    'CCP6' => 'Caniapiscau',
    'CCP5' => 'Rawdon/Camping Pontbriand (Hydro) Seaplane Base',
    'CCP3' => 'Chute-St-Philippe',
    'CCH7' => 'Québec/Capitale Hélicoptère Heliport',
    'CCH5' => 'Montréal/Longueuil (Centre Hospitalier Pierre-Boucher), Heliport',
    'CBS6' => 'Blue Sea Lake (Outaouais Aviation) Seaplane Base',
    'CBB8' => 'Ste-Barbe Heliport',
    'CAX7' => 'Minstrel Island Seaplane Base',
    'cas8' => 'Seaplane Base',
    'CAS8' => 'Roberval (Air Saguenay) Seaplane Base',
    'CAL8' => 'Ste-Anne-du-Lac (Aviation PLMG Inc.)',
    'CAA4' => 'St-Apollinaire (AirPro)',
    'CAA2' => 'St-André-Avellin'

];

?>